# CI workflow to build, test, and lint the CRUD app on push or pull request
name: CI Pipeline2
on:
  push:
    branches: [main] # Trigger on pushes to main branch
  pull_request:
    branches: [main] # Trigger on PRs to main branch
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest # Use GitHub's free Linux runner
    steps:
      - uses: actions/checkout@v3 # Check out the repository code
      - name: Set up Node.js # Install Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use Node.js 18 for consistency
      - name: Cache dependencies # 1
        uses: actions/cache@v3
        with:
          path: ~/.npm # Cache npm’s global cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # Key based on OS and package-lock.json
      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Run testing
        working-directory: backend
        run: npm test

  build_scan_push:
    needs: test
    runs-on: ubuntu-latest
    steps:     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::070238932258:role/GitHub_Actions_ECR_Role 
          aws-region: ap-southeast-2

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Compute image ref
        id: vars
        run: echo "image=${{ steps.ecr.outputs.registry }}/my-ecr-repo:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Trivy filesystem scan (repo)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret,misconfig
          format: json
          output: trivy-fs-report.json
          severity: CRITICAL,HIGH,MEDIUM,LOW
          ignore-unfixed: true
          exit-code: 0 
      - name: Upload FS scan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.json
          retention-days: 30

      # --- Trivy dependency scan (frontend only) ---
      - name: Trivy dependency scan (frontend)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: frontend
          scanners: vuln
          vuln-type: library
          dependency-tree: true
          format: json
          output: trivy-deps-report.json
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 0   # set to 1 to enforce failure on HIGH/CRITICAL

      - name: Upload dependency scan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-deps-report
          path: trivy-deps-report.json
          retention-days: 30      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v3 # Check out the repository code
      - name: Build image (load to runner for scanning)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: |
            ${{ steps.vars.outputs.image }}
          load: true           # makes the image available locally for Trivy
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.vars.outputs.image }}
          format: json
          output: trivy-report.json
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Upload Vulnerability Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 30

      - name: Push image to Amazon ECR (only runs if Trivy passed)
        run: docker push "${{ steps.vars.outputs.image }}"
